version: "3.4"
services:
  react-app:
    image: chandhudev0/image-e-commerce:client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: chandhudev0/image-e-commerce:server
    env_file:
      - .env
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
